# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "xCoffeeManx" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "npub1hj2xazg3k6dg07kj4d5k7ydcneha7flqtn8lgufkqfnamhh9mmcsak95re" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title:  xCoffeeManx | Links # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#212121"
  # cover_color: "#515A5A"

# Configuración Central
main:
  title: xCoffeeManx # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Twitter
    icon: twitter
    url: https://twitter.com/AnthonyMendozaG

  - title: Nostr
    icon: nostr
    url: https://iris.to/coffeeman
    npub: "npub1hj2xazg3k6dg07kj4d5k7ydcneha7flqtn8lgufkqfnamhh9mmcsak95re" # Entre comillas dobles

  - title: Telegram
    icon: telegram
    url: https://t.me/AnthonyMendozaG
 
  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/anthonymendozag/
 
#  - title: Github
#    icon: github
#    url: https://github.com/xCoffeeManx
    
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/anthony-mendoza-g-2a669340 # Link a donde redireccionará al hacer click


# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
